entries/blueprint.py
import os
from flask import Blueprint, flash, redirect, render_template, request, url_for, g
from helpers import object_list
from models import Entry, Tag, entry_tags
from entries.forms import EntryForm, ImageForm
from app import app, db
from werkzeug.utils import secure_filename
from flask_login import login_required

entries = Blueprint('entries', __name__, template_folder='templates')


@entries.route('/')
def index():
    """List all blog entries ordered by date of creation."""
    entries = Entry.query.order_by(Entry.created_timestamp.desc())
    return entry_list('entries/index.html', entries)


@entries.route('/tags/')
def tag_index():
    """List all tags."""
    tags = Tag.query.join(entry_tags).distinct().order_by(Tag.name)
    return object_list('entries/tag_index.html', tags)


@entries.route('/tags/<slug>/')
def tag_detail(slug):
    """Show list of blog entries with the given tag."""
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    entries = tag.entries.order_by(Entry.created_timestamp.desc())
    return entry_list('entries/tag_detail.html', entries, tag=tag)


@entries.route('/image-upload/', methods=['GET', 'POST'])
@login_required
def image_upload():
    if request.method == 'POST':
        form = ImageForm(request.form)
        if form.validate():
            image_file = request.files['file']
            filename = os.path.join(app.config['IMAGES_DIR'], secure_filename(image_file.filename))
            if filename.split('.')[-1] not in ('png', 'jpg', 'tiff', 'gif'):
                flash('Error: "{}" does not have a supported format.'.format(os.path.basename(filename)), 'danger')
                return redirect(url_for('entries.index'))
            image_file.save(filename)
            flash('Saved "{}"'.format(os.path.basename(filename)), 'success')
            return redirect(url_for('entries.index'))
    else:  # If GET request received.
        form = ImageForm()
    return render_template('entries/image_upload.html', form=form)


@entries.route('/create/', methods=['GET', 'POST'])
@login_required
def create():
    if request.method == 'POST':
        form = EntryForm(request.form)
        if form.validate():
            from app import db
            entry = form.save_entry(Entry(author=g.user))
            db.session.add(entry)
            db.session.commit()
            flash('Entry "{}" created successfully.'.format(entry.title), 'success')
            return redirect(url_for('entries.detail', slug=entry.slug))
    else:  # If GET request received.
        form = EntryForm()
    return render_template('entries/create.html', form=form)


@entries.route('/<slug>/')
def detail(slug):
    """Show the given entry."""
    entry = get_entry_or_404(slug)
    return render_template('entries/detail.html', entry=entry)


@entries.route('/<slug>/edit/', methods=['GET', 'POST'])
@login_required
def edit(slug):
    """Show the form for editing an entry (GET) or save the edited entry(POST)."""
    entry = get_entry_or_404(slug, author=None)
    if request.method == 'POST':
        # Fill a form model with data from page form.
        form = EntryForm(request.form, obj=entry)
        if form.validate():
            # Save data from form model to database entry.
            entry = form.save_entry(entry)
            db.session.add(entry)
            db.session.commit()
            flash('Entry "{}" has been saved.'.format(entry.title), 'success')
            # Redirect to the edited entry detail view.
            return redirect(url_for('entries.detail', slug=entry.slug))
    else:
        form = EntryForm(obj=entry)
    return render_template('entries/edit.html', entry=entry, form=form)


@entries.route('/<slug>/delete/', methods=['GET', 'POST'])
@login_required
def delete(slug):
    """Show the form for deleting an entry (GET) or delete the entry(POST)."""
    entry = get_entry_or_404(slug, author=None)
    if request.method == 'POST':
        entry.status = Entry.STATUS_DELETED
        db.session.add(entry)
        db.session.commit()
        flash('Entry "{}" has been deleted.'.format(entry.title), 'success')
        return redirect(url_for('entries.index'))

    return render_template('entries/delete.html', entry=entry)


def entry_list(template, query, **context):
    """Filter a given query by 'q' parameter and insert it into given template."""
    query = filter_status_by_user(query)
    valid_statuses = (Entry.STATUS_PUBLIC, Entry.STATUS_DRAFT)
    query = query.filter(Entry.status.in_(valid_statuses))
    search = request.args.get('q')
    if search:
        query = query.filter(
            Entry.status == (Entry.body.contains(search)) | (Entry.title.contains(search)))

    return object_list(template, query, **context)


def get_entry_or_404(slug, author=None):
    query = Entry.query.filter(Entry.slug == slug)
    if author:
        query = query.filter(Entry.author == author)
    else:
        query = filter_status_by_user(query)
    return query.first_or_404()


def filter_status_by_user(query):
    """Return all the public entries, or the undeleted entries for which author is logged in."""
    if not g.user.is_authenticated:
        return query.filter(Entry.status == Entry.STATUS_PUBLIC)
    else:
        # Allow user to view their own drafts.
        query = query.filter(
            (Entry.status == Entry.STATUS_PUBLIC) |
            ((Entry.author == g.user) &
             (Entry.status != Entry.STATUS_DELETED)))
    return query

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %} | Blog site</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">

    {% block extra_styles %} {% endblock %}

    <script src="{{ url_for('static', filename='js/jquery-3.2.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    {% block extra_scripts %} {% endblock %}
</head>

<body class="{% block body_class %} {% endblock %}">
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">{% block branding %} My Blog {% endblock %} </a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('homepage') }}">Home</a></li>
                    <li><a href="{{ url_for('entries.index') }}">Blog</a></li>
                    <li><a href="{{ url_for('entries.tag_index') }}">Tags</a></li>
                    {% if g.user.is_authenticated %}
                        <li><a href="{{ url_for('logout', next=request.path) }}">Log out</a></li>
                        {% else %}
                        <li><a href="{{ url_for('login', next=request.path) }}">Log in</a></li>
                    {% endif %}
                    {% block extra_nav %} {% endblock %}
                </ul>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <h1>{% block content_title %} {% endblock %} </h1>
                {% for category, message in get_flashed_messages(with_categories=true) %}
                    <div class="alert alert-dismissable alert-{{category}} {{category}}">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        {{ message }}
                    </div>
                {% endfor %}
                {% block content %}
                {% endblock %}
            </div>
            <div class="col-md-3">
                {% block sidebar %}
                {% endblock %}
            </div>
        </div>

        <div class="row">
            <hr />
            <footer>
                <p>&copy; mjarosie</p>
            </footer>
        </div>
    </div>
</body>
</html>

templates/homepage.html
{% extends "base.html" %}

{% block content_title %} Welcome to my website {% endblock %}

{% block content %}
    <p>Hello, {{ name|default('anonymous', True) }}.</p>
    <div class="col-md-offset-1 col-sm-3">This is the test blog application developed in order to learn using Flask python microframework.</div>
    <div>
        <a href="{{ url_for('entries.create') }}">Click to create a new entry</a>
    </div>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% from "macros/form_field.html" import form_field %}
{% block title %}Log in{% endblock %}
{% block content_title %}Log in{% endblock %}
{% block content %}
    <form action="{{ url_for('login', next=request.args.get('next','')) }}" class="form form-horizontal" method="post">
        {{ form_field(form.email) }}
        {{ form_field(form.password) }}
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <div class="checkbox">
                    <label>{{ form.remember_me() }} Remember me</label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <button type="submit" class="btn btn-default">Log in</button>
                <a class="btn" href="{{ url_for('homepage') }}">Cancel</a>
            </div>
        </div>
    </form>
{% endblock %}