entries/forms.py
import wtforms
from wtforms.validators import DataRequired

from models import Entry, Tag


class TagField(wtforms.StringField):
    def _value(self):
        if self.data:
            # Display tags as a comma-separated list.
            return ', '.join([tag.name for tag in self.data])
        return ''

    def get_tags_from_string(self, tag_string):
        raw_tags = tag_string.split(',')

        # Filter out empty tags.
        tag_names = [name.strip() for name in raw_tags if name.strip()]

        # Query for any tags that are already saved.
        existing_tags = Tag.query.filter(Tag.name.in_(tag_names))

        # Derive tags with new names.
        new_names = set(tag_names) - set([tag.name for tag in existing_tags])

        # Create a list of unsaved Tag instances for the new tags.
        new_tags = [Tag(name=name)
                    for name
                    in new_names
                    ]

        return list(existing_tags) + new_tags

    def process_formdata(self, valuelist):
        if valuelist:
            self.data = self.get_tags_from_string(valuelist[0])
        else:
            self.data = []


class EntryForm(wtforms.Form):
    """Form used to create new blog entries. Both title and body are required."""
    title = wtforms.StringField('Title', validators=[DataRequired()])
    body = wtforms.TextAreaField('Body', validators=[DataRequired()])
    status = wtforms.SelectField(
        'Entry status',
        choices=(
            (Entry.STATUS_PUBLIC, 'Public'),
            (Entry.STATUS_DRAFT, 'Draft')
        ),
        coerce=int
    )
    tags = TagField('Tags', description='Separate multiple tags with commas.')
    slug = wtforms.StringField('User-friendly URL', render_kw={'readonly': True})

    def save_entry(self, entry):
        """Populates the given entry with the form data and re-generates the entry's slug based on the new title."""
        self.populate_obj(entry)
        entry.generate_slug()
        return entry

class ImageForm(wtforms.Form):
    file = wtforms.FileField('Image file')

entries/blueprint.py
import os
from flask import Blueprint, flash, redirect, render_template, request, url_for, g
from helpers import object_list
from models import Entry, Tag, entry_tags
from entries.forms import EntryForm, ImageForm
from app import app, db
from werkzeug.utils import secure_filename
from flask_login import login_required

entries = Blueprint('entries', __name__, template_folder='templates')


@entries.route('/')
def index():
    """List all blog entries ordered by date of creation."""
    entries = Entry.query.order_by(Entry.created_timestamp.desc())
    return entry_list('entries/index.html', entries)


@entries.route('/tags/')
def tag_index():
    """List all tags."""
    tags = Tag.query.join(entry_tags).distinct().order_by(Tag.name)
    return object_list('entries/tag_index.html', tags)


@entries.route('/tags/<slug>/')
def tag_detail(slug):
    """Show list of blog entries with the given tag."""
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    entries = tag.entries.order_by(Entry.created_timestamp.desc())
    return entry_list('entries/tag_detail.html', entries, tag=tag)


@entries.route('/image-upload/', methods=['GET', 'POST'])
@login_required
def image_upload():
    if request.method == 'POST':
        form = ImageForm(request.form)
        if form.validate():
            image_file = request.files['file']
            filename = os.path.join(app.config['IMAGES_DIR'], secure_filename(image_file.filename))
            if filename.split('.')[-1] not in ('png', 'jpg', 'tiff', 'gif'):
                flash('Error: "{}" does not have a supported format.'.format(os.path.basename(filename)), 'danger')
                return redirect(url_for('entries.index'))
            image_file.save(filename)
            flash('Saved "{}"'.format(os.path.basename(filename)), 'success')
            return redirect(url_for('entries.index'))
    else:  # If GET request received.
        form = ImageForm()
    return render_template('entries/image_upload.html', form=form)


@entries.route('/create/', methods=['GET', 'POST'])
@login_required
def create():
    if request.method == 'POST':
        form = EntryForm(request.form)
        if form.validate():
            from app import db
            entry = form.save_entry(Entry(author=g.user))
            db.session.add(entry)
            db.session.commit()
            flash('Entry "{}" created successfully.'.format(entry.title), 'success')
            return redirect(url_for('entries.detail', slug=entry.slug))
    else:  # If GET request received.
        form = EntryForm()
    return render_template('entries/create.html', form=form)


@entries.route('/<slug>/')
def detail(slug):
    """Show the given entry."""
    entry = get_entry_or_404(slug)
    return render_template('entries/detail.html', entry=entry)


@entries.route('/<slug>/edit/', methods=['GET', 'POST'])
@login_required
def edit(slug):
    """Show the form for editing an entry (GET) or save the edited entry(POST)."""
    entry = get_entry_or_404(slug, author=None)
    if request.method == 'POST':
        # Fill a form model with data from page form.
        form = EntryForm(request.form, obj=entry)
        if form.validate():
            # Save data from form model to database entry.
            entry = form.save_entry(entry)
            db.session.add(entry)
            db.session.commit()
            flash('Entry "{}" has been saved.'.format(entry.title), 'success')
            # Redirect to the edited entry detail view.
            return redirect(url_for('entries.detail', slug=entry.slug))
    else:
        form = EntryForm(obj=entry)
    return render_template('entries/edit.html', entry=entry, form=form)


@entries.route('/<slug>/delete/', methods=['GET', 'POST'])
@login_required
def delete(slug):
    """Show the form for deleting an entry (GET) or delete the entry(POST)."""
    entry = get_entry_or_404(slug, author=None)
    if request.method == 'POST':
        entry.status = Entry.STATUS_DELETED
        db.session.add(entry)
        db.session.commit()
        flash('Entry "{}" has been deleted.'.format(entry.title), 'success')
        return redirect(url_for('entries.index'))

    return render_template('entries/delete.html', entry=entry)


def entry_list(template, query, **context):
    """Filter a given query by 'q' parameter and insert it into given template."""
    query = filter_status_by_user(query)
    valid_statuses = (Entry.STATUS_PUBLIC, Entry.STATUS_DRAFT)
    query = query.filter(Entry.status.in_(valid_statuses))
    search = request.args.get('q')
    if search:
        query = query.filter(
            Entry.status == (Entry.body.contains(search)) | (Entry.title.contains(search)))

    return object_list(template, query, **context)


def get_entry_or_404(slug, author=None):
    query = Entry.query.filter(Entry.slug == slug)
    if author:
        query = query.filter(Entry.author == author)
    else:
        query = filter_status_by_user(query)
    return query.first_or_404()


def filter_status_by_user(query):
    """Return all the public entries, or the undeleted entries for which author is logged in."""
    if not g.user.is_authenticated:
        return query.filter(Entry.status == Entry.STATUS_PUBLIC)
    else:
        # Allow user to view their own drafts.
        query = query.filter(
            (Entry.status == Entry.STATUS_PUBLIC) |
            ((Entry.author == g.user) &
             (Entry.status != Entry.STATUS_DELETED)))
    return query

entries/templates/entries/base_entries.html
{% extends "base.html" %}

{% block sidebar %}
    <form class="form-inline well" method="get" role="form">
        <div class="input-group">
            <input class="form-control input-xs" name="q" placeholder="Search..." value="{{ request.args.get('q', '') }}" />
            <span class="input-group-btn">
                <button class="btn btn-default" type="submit">Go</button>
            </span>
        </div>
    </form>
{% endblock %}

{% block content %}
    {% include "includes/list.html" %}
    {% include "includes/page_links.html" %}
{% endblock %}

entries/templates/entries/create.html
{% extends "base.html" %}

{% block title %}Create new entry{% endblock %}

{% block content_title%}Create new entry{% endblock %}

{% block content %}
    <form action="{{ url_for('entries.create') }}" class="form form-horizontal" method="post">
        <!-- Show label and entry field for each field of form. -->
        {% for field in form %}
            <div class="form-group {% if field.errors %} has-error has-feedback {% endif %}">
                {{ field.label(class='col-sm-3 control-label') }}
                <div class="col-sm-9">
                    {{ field(class='form-control') }}
                    {% if field.errors %}
                        <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
                    {% endif %}
                    {% for error in field.errors %}
                        <span class="help-block">{{ error }} </span>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}

        <!-- Show buttons for submitting the form and cancel (then it returns to the main index of blog entries). -->
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <button type="submit" class="btn btn-default">Create</button>
                <a class="btn" href="{{ url_for('entries.index') }}">Cancel</a>
            </div>
        </div>
    </form>
{% endblock %}

entries/templates/entries/delete.html
{% extends "base.html" %}

{% block title %}{{ entry.title }} {% endblock %}

{% block content_title %} {{ entry.title }} {% endblock %}

{% block content %}
    <form action="{{ url_for('entries.delete', slug=entry.slug) }}" method="post">
        <fieldset>
            <legend>Delete this entry?</legend>
            <button class="btn btn-danger" type="submit">Delete</button>
            <a class="btn" href="{{ url_for('entries.detail', slug=entry.slug) }}">Cancel</a>
        </fieldset>
    </form>
{% endblock %}

entries/templates/entries/detail.html
{% extends "base.html" %}

<!--
Attributes:
    entry: Entry to be displayed.
-->

{% block title %} {{ entry.title }} {% endblock %}

{% block content_title %} {{ entry.title }} {% endblock %}

<!-- List all the tags connected with the entry, sorted in alphabetical order. -->
{% block sidebar %}
    <ul class="well nav nav-list">
        {% if g.user == entry.author %}
            <li><h4>Actions</h4></li>
            <li><a href="{{ url_for('entries.edit', slug=entry.slug) }}">Edit</a></li>
            <li><a href="{{ url_for('entries.delete', slug=entry.slug) }}">Delete</a></li>
        {% endif %}
        <li><h4>Tags</h4></li>
        {% for tag in entry.tags|sort(attribute='name') %}
            <li><a href="{{ url_for('entries.tag_detail', slug=tag.slug) }}">{{ tag.name }}</a></li>
        {% endfor %}
    </ul>

<p>Published {{entry.created_timestamp.strftime('%d/%m/%Y') }}</p>

{% endblock %}

{% block content %}
{{ entry.body }}
{% endblock %}

entries/templates/entries/edit.html
{% extends "base.html" %}
{% from "macros/form_field.html" import form_field %}

{% block title %}Edit {{ entry.title }}{% endblock %}

{% block content_title%}Edit {{ entry.title }}{% endblock %}

{% block content %}
    <form action="{{ url_for('entries.edit', slug=entry.slug) }}" class="form form-horizontal" method="post">
        <!-- Show label and entry field for each field of form using macro. -->
        {% for field in form %}
            {{ form_field(field) }}
        {% endfor %}

        <!-- Show buttons for submitting the form and cancel (then it returns to the main index of blog entries). -->
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <button type="submit" class="btn btn-default">Save</button>
                <a class="btn" href="{{ url_for('entries.detail', slug=entry.slug) }}">Cancel</a>
            </div>
        </div>
    </form>
{% endblock %}

entries/templates/entries/image_upload.html
{% extends "base.html" %}
{% from "macros/form_field.html" import form_field %}

{% block title %}Upload an image{% endblock %}

{% block content_title %}Upload an image{% endblock %}

{% block content %}
    <form action="{{ url_for('entries.image_upload') }}" enctype="multipart/form-data" method="post">
        {% for field in form %}
            {{ form_field(field) }}
        {% endfor %}
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <button type="submit" class="btn btn-default">Upload</button>
                <a class="btn" href="{{ url_for('entries.index') }}">Cancel</a>
            </div>
        </div>
    </form>
{% endblock %}

entries/templates/entries/index.html
{% extends "entries/base_entries.html" %}

{% block title %}Entries{% endblock %}

{% block content_title %}Entries {% endblock %}

entries/templates/entries/tag_detail.html
{% extends "entries/base_entries.html" %}

{% block title %} Entries tagged with "{{tag.name}}"  {% endblock %}

{% block content_title %} Entries tagged with "{{tag.name}}" {% endblock %}

entries/templates/entries/tag_index.html
{% extends "base.html" %}

{% block title %}Tags{% endblock %}

{% block content_title %}Tags{% endblock %}

{% block content %}
    <ul>
        {% for tag in object_list.items %}
        <li><a href="{{ url_for('entries.tag_detail', slug=tag.slug) }}">{{ tag.name }}</a></li>
        {% endfor %}
    </ul>

    {% include "includes/page_links.html" %}
{% endblock %}